package com.subia.android.ui

/** Devuelve el dominio del servicio para cargar su logo, o cadena vacía si no se reconoce. */
fun getLogoDomain(nombre: String): String {
    val n = nombre.lowercase()
    return when {
        "netflix" in n -> "netflix.com"
        "spotify" in n -> "spotify.com"
        "amazon prime" in n || "prime video" in n -> "primevideo.com"
        "amazon music" in n -> "music.amazon.com"
        "amazon" in n -> "amazon.com"
        "youtube premium" in n -> "youtube.com"
        "youtube" in n -> "youtube.com"
        "disney" in n -> "disneyplus.com"
        "chatgpt" in n || "openai" in n -> "openai.com"
        "claude" in n || "anthropic" in n -> "anthropic.com"
        "cursor" in n -> "cursor.com"
        "github copilot" in n || "copilot" in n -> "github.com"
        "github" in n -> "github.com"
        "gitlab" in n -> "gitlab.com"
        "gemini" in n -> "gemini.google.com"
        "grok" in n -> "x.ai"
        "perplexity" in n -> "perplexity.ai"
        "midjourney" in n -> "midjourney.com"
        "microsoft 365" in n || "office 365" in n || "m365" in n -> "microsoft.com"
        "microsoft" in n -> "microsoft.com"
        "onedrive" in n -> "onedrive.live.com"
        "google one" in n -> "one.google.com"
        "google" in n -> "google.com"
        "icloud" in n -> "icloud.com"
        "apple tv" in n -> "tv.apple.com"
        "apple music" in n -> "music.apple.com"
        "apple arcade" in n -> "apple.com"
        "apple fitness" in n -> "apple.com"
        "apple" in n -> "apple.com"
        "notion" in n -> "notion.so"
        "figma" in n -> "figma.com"
        "canva" in n -> "canva.com"
        "adobe" in n -> "adobe.com"
        "grammarly" in n -> "grammarly.com"
        "todoist" in n -> "todoist.com"
        "duolingo" in n -> "duolingo.com"
        "jetbrains" in n -> "jetbrains.com"
        "affinity" in n -> "affinity.serif.com"
        "dropbox" in n -> "dropbox.com"
        "backblaze" in n -> "backblaze.com"
        "pcloud" in n -> "pcloud.com"
        "nordvpn" in n -> "nordvpn.com"
        "expressvpn" in n -> "expressvpn.com"
        "mullvad" in n -> "mullvad.net"
        "protonvpn" in n || "proton vpn" in n -> "protonvpn.com"
        "proton" in n -> "proton.me"
        "1password" in n -> "1password.com"
        "bitwarden" in n -> "bitwarden.com"
        "malwarebytes" in n -> "malwarebytes.com"
        "xbox" in n -> "xbox.com"
        "ps plus" in n || "playstation" in n -> "playstation.com"
        "nintendo" in n -> "nintendo.com"
        "ea play" in n || "ea " in n -> "ea.com"
        "humble" in n -> "humblebundle.com"
        "crunchyroll" in n -> "crunchyroll.com"
        "dazn" in n -> "dazn.com"
        "max" in n && ("hbo" in n || "warner" in n) -> "max.com"
        "hulu" in n -> "hulu.com"
        "paramount" in n -> "paramountplus.com"
        "movistar" in n -> "movistar.es"
        "filmin" in n -> "filmin.es"
        "tidal" in n -> "tidal.com"
        "deezer" in n -> "deezer.com"
        "audible" in n -> "audible.com"
        "kindle" in n -> "amazon.com"
        "readwise" in n -> "readwise.io"
        "scribd" in n -> "scribd.com"
        "blinkist" in n -> "blinkist.com"
        "strava" in n -> "strava.com"
        "whoop" in n -> "whoop.com"
        "garmin" in n -> "garmin.com"
        "myfitnesspal" in n -> "myfitnesspal.com"
        "calm" in n -> "calm.com"
        "headspace" in n -> "headspace.com"
        "vercel" in n -> "vercel.com"
        "railway" in n -> "railway.app"
        "sentry" in n -> "sentry.io"
        "datadog" in n -> "datadoghq.com"
        "linear" in n -> "linear.app"
        "postman" in n -> "postman.com"
        // Recibos recurrentes (gimnasios, suministros, alarmas, telecos, seguros, transporte):
        // mismos dominios que el catálogo del backend, para que no salgan con la inicial.
        "basic-fit" in n -> "basic-fit.com"
        "basic fit" in n -> "basic-fit.com"
        "vivagym" in n -> "vivagym.es"
        "synergym" in n -> "synergym.es"
        "mcfit" in n -> "mcfit.com"
        "anytime fitness" in n -> "anytimefitness.es"
        "go fit" in n -> "go-fit.es"
        "holmes place" in n -> "holmesplace.com"
        "iberdrola" in n -> "iberdrola.es"
        "endesa" in n -> "endesa.com"
        "naturgy" in n -> "naturgy.es"
        "repsol" in n -> "repsol.es"
        "totalenergies" in n -> "totalenergies.es"
        "holaluz" in n -> "holaluz.com"
        "octopus" in n -> "octopusenergy.es"
        "edp" in n -> "edpenergia.es"
        "plenitude" in n -> "eniplenitude.com"
        "factor energ" in n -> "factorenergia.com"
        "audax" in n -> "audaxrenovables.com"
        "gana energ" in n -> "ganaenergia.com"
        "canal de isabel" in n -> "canaldeisabelsegunda.es"
        "aigües de barcelona" in n -> "aiguesdebarcelona.cat"
        "aigues de barcelona" in n -> "aiguesdebarcelona.cat"
        "emasesa" in n -> "emasesa.com"
        "global omnium" in n -> "globalomnium.com"
        "emaya" in n -> "emaya.es"
        "aqualia" in n -> "aqualia.com"
        "hidralia" in n -> "hidralia-sa.es"
        "securitas" in n -> "securitasdirect.es"
        "prosegur" in n -> "prosegur.es"
        "adt" in n -> "adt.es"
        "tyco" in n -> "tyco.es"
        "vodafone" in n -> "vodafone.es"
        "orange" in n -> "orange.es"
        "digi" in n -> "digimobil.es"
        "másmóvil" in n -> "masmovil.es"
        "masmovil" in n -> "masmovil.es"
        "yoigo" in n -> "yoigo.com"
        "pepephone" in n -> "pepephone.com"
        "lowi" in n -> "lowi.es"
        "simyo" in n -> "simyo.es"
        "finetwork" in n -> "finetwork.com"
        "jazztel" in n -> "jazztel.com"
        "euskaltel" in n -> "euskaltel.com"
        "avatel" in n -> "avatel.es"
        "adamo" in n -> "adamo.es"
        "mapfre" in n -> "mapfre.es"
        "axa" in n -> "axa.es"
        "allianz" in n -> "allianz.es"
        "mutua" in n -> "mutua.es"
        "línea directa" in n -> "lineadirecta.com"
        "linea directa" in n -> "lineadirecta.com"
        "génesis" in n -> "genesis.es"
        "genesis" in n -> "genesis.es"
        "pelayo" in n -> "pelayo.com"
        "reale" in n -> "reale.es"
        "generali" in n -> "generali.es"
        "zurich" in n -> "zurich.es"
        "caser" in n -> "caser.es"
        "catalana occidente" in n -> "catalanaoccidente.com"
        "ocaso" in n -> "ocaso.es"
        "santalucía" in n -> "santalucia.es"
        "santalucia" in n -> "santalucia.es"
        "fiatc" in n -> "fiatc.es"
        "verti" in n -> "verti.es"
        "qualitas" in n -> "qualitasauto.com"
        "balumba" in n -> "balumba.es"
        "sanitas" in n -> "sanitas.es"
        "adeslas" in n -> "adeslas.es"
        "dkv" in n -> "dkv.es"
        "asisa" in n -> "asisa.es"
        "cosalud" in n -> "cosalud.com"
        "barkibu" in n -> "barkibu.com"
        "santévet" in n -> "santevet.es"
        "santevet" in n -> "santevet.es"
        "crtm" in n -> "crtm.es"
        "abono transporte" in n -> "crtm.es"
        "bicimad" in n -> "bicimad.com"
        "bicing" in n -> "bicing.barcelona"
        "uber one" in n -> "uber.com"
        "via-t" in n -> "bipdrive.com"
        else -> ""
    }
}
