package com.subia.android.ui

fun getLogoUrl(nombre: String): String {
    val n = nombre.lowercase()
    val domain = when {
        "netflix" in n -> "netflix.com"
        "spotify" in n -> "spotify.com"
        "amazon prime" in n || "prime video" in n -> "primevideo.com"
        "amazon music" in n -> "music.amazon.com"
        "amazon" in n -> "amazon.com"
        "youtube premium" in n -> "youtube.com"
        "youtube" in n -> "youtube.com"
        "disney" in n -> "disneyplus.com"
        "chatgpt" in n || "openai" in n -> "openai.com"
        "claude" in n || "anthropic" in n -> "anthropic.com"
        "cursor" in n -> "cursor.com"
        "github copilot" in n || "copilot" in n -> "github.com"
        "github" in n -> "github.com"
        "gitlab" in n -> "gitlab.com"
        "gemini" in n -> "gemini.google.com"
        "grok" in n -> "x.ai"
        "perplexity" in n -> "perplexity.ai"
        "midjourney" in n -> "midjourney.com"
        "microsoft 365" in n || "office 365" in n || "m365" in n -> "microsoft.com"
        "microsoft" in n -> "microsoft.com"
        "onedrive" in n -> "onedrive.live.com"
        "google one" in n -> "one.google.com"
        "google" in n -> "google.com"
        "icloud" in n -> "icloud.com"
        "apple tv" in n -> "tv.apple.com"
        "apple music" in n -> "music.apple.com"
        "apple arcade" in n -> "apple.com"
        "apple fitness" in n -> "apple.com"
        "apple" in n -> "apple.com"
        "notion" in n -> "notion.so"
        "figma" in n -> "figma.com"
        "canva" in n -> "canva.com"
        "adobe" in n -> "adobe.com"
        "grammarly" in n -> "grammarly.com"
        "todoist" in n -> "todoist.com"
        "duolingo" in n -> "duolingo.com"
        "jetbrains" in n -> "jetbrains.com"
        "affinity" in n -> "affinity.serif.com"
        "dropbox" in n -> "dropbox.com"
        "backblaze" in n -> "backblaze.com"
        "pcloud" in n -> "pcloud.com"
        "nordvpn" in n -> "nordvpn.com"
        "expressvpn" in n -> "expressvpn.com"
        "mullvad" in n -> "mullvad.net"
        "protonvpn" in n || "proton vpn" in n -> "protonvpn.com"
        "proton" in n -> "proton.me"
        "1password" in n -> "1password.com"
        "bitwarden" in n -> "bitwarden.com"
        "malwarebytes" in n -> "malwarebytes.com"
        "xbox" in n -> "xbox.com"
        "ps plus" in n || "playstation" in n -> "playstation.com"
        "nintendo" in n -> "nintendo.com"
        "ea play" in n || "ea " in n -> "ea.com"
        "humble" in n -> "humblebundle.com"
        "crunchyroll" in n -> "crunchyroll.com"
        "dazn" in n -> "dazn.com"
        "max" in n && ("hbo" in n || "warner" in n) -> "max.com"
        "hulu" in n -> "hulu.com"
        "paramount" in n -> "paramountplus.com"
        "movistar" in n -> "movistar.es"
        "filmin" in n -> "filmin.es"
        "tidal" in n -> "tidal.com"
        "deezer" in n -> "deezer.com"
        "audible" in n -> "audible.com"
        "kindle" in n -> "amazon.com"
        "readwise" in n -> "readwise.io"
        "scribd" in n -> "scribd.com"
        "blinkist" in n -> "blinkist.com"
        "strava" in n -> "strava.com"
        "whoop" in n -> "whoop.com"
        "garmin" in n -> "garmin.com"
        "myfitnesspal" in n -> "myfitnesspal.com"
        "calm" in n -> "calm.com"
        "headspace" in n -> "headspace.com"
        "vercel" in n -> "vercel.com"
        "railway" in n -> "railway.app"
        "sentry" in n -> "sentry.io"
        "datadog" in n -> "datadoghq.com"
        "linear" in n -> "linear.app"
        "postman" in n -> "postman.com"
        else -> null
    } ?: return ""
    return "https://logo.clearbit.com/$domain"
}
