services:
  - type: web
    name: subia-backend
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AIVEN_DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_AUTH_PASSWORD
        sync: false