CREATE TABLE categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    color VARCHAR(20)  NOT NULL DEFAULT '#6c757d',
    icon  VARCHAR(50)  NOT NULL DEFAULT ''
);

CREATE TABLE subscriptions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)   NOT NULL,
    description  VARCHAR(500)   NOT NULL DEFAULT '',
    price        DECIMAL(10, 2) NOT NULL,
    currency     VARCHAR(10)    NOT NULL DEFAULT 'EUR',
    billing_cycle VARCHAR(20)   NOT NULL,
    renewal_date DATE           NOT NULL,
    category_id  BIGINT         NOT NULL REFERENCES categories(id),
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    notes        VARCHAR(1000)  NOT NULL DEFAULT ''
);
