CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(254)  NOT NULL UNIQUE,
    password_hash   VARCHAR(72),
    google_id       VARCHAR(128)  UNIQUE,
    email_verified  BOOLEAN       NOT NULL DEFAULT FALSE,
    email_verification_token      VARCHAR(64),
    email_verification_expires_at TIMESTAMPTZ,
    failed_attempts INT           NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    role            VARCHAR(20)   NOT NULL DEFAULT 'USER',
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_users_email     ON users(email);
CREATE INDEX idx_users_google_id ON users(google_id) WHERE google_id IS NOT NULL;
